name: covid
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.10
  shared_preferences: ^0.5.7+3
  http: ^0.12.1
  cached_network_image: ^2.2.0+1
  dynamic_theme: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

